### ISSUE TITLE
parse tree structure

### ISSUE THREAD

**Issue by zdgithub** [yaushian/Tree-Transformer#2]
Hi, thanks for your interesting work!

After reading the paper, I wonder why the parse tree may have three branches except the leaf nodes as shown in your paper `Figure 3`.  For example, in your `Figure 3`,  the root node have three subtrees.

**Comment by yaushian** [comment]
Hi, thanks for being interested in our work!

In Algorithm 1, if the probability of a maximum breakpoint is above the threshold and the current parsing layer is the minimum layer "m", it will return all the nodes beneath the current root as its subtree. Please see Algorithm 1 line 10-12.

**Comment by zdgithub** [comment]
Thank you, I know why the leaf node such as `some market makers` in Figure 3 is not binary, but I don't know why the root node of the tree has three branches.

**Comment by yaushian** [comment]
That is because we made a mistake when drawing the parse tree by ourselves. The original parse tree drawn by NLTK is this: ![image](https://user-images.githubusercontent.com/7030677/67625158-c7938100-f86c-11e9-91c0-595c0f3603c7.png). 
Thank you for pointing out this mistake in our paper. We will revise it.
