### ISSUE TITLE
The group_prob & break_prob

### ISSUE THREAD

**Issue by MjolnirX** [yaushian/Tree-Transformer#3]
in model.py,line 50
`group_prob,break_prob = self.group_attn(x, mask, group_prob)`may be
`group_prob,break_prob = self.group_attn(x, mask, break_prob)`?
cause the break_prob is neibor_attn in GroupAttention, which is the **a** in paper.

**Comment by yaushian** [comment]
Yes, considering the code semantic meaning, it should be `group_prob,break_prob = self.group_attn(x, mask, break_prob)`.  However, this will not influence the result because we only need `break_prob[batch_id, i, i+1]` to implement eq. (8) in paper and `group_prob[batch_id, i, i+1]` is the same as `break_prob[batch_id, i, i+1]`. Thank you for pointing out this confusing variable.
